### PR TITLE
add compiling of translation files

### PR DESCRIPTION
**Pull request by jjw24**
add compiling of translation files to ci

close https://github.com/deefrawley/Flow.Launcher.Plugin.Currency/issues/7

### CODE REVIEW

**Comment by deefrawley** [comment]
Not sure this will work. Babel is a Python wrapper for gettext and other things. Msgfmt is a linux binary that calls GNU gettext. I think you need to do the `sudo apt get` instead of installing the requirements-dev, like @pc223  posted in the issue.

**Comment by jjw24** [comment]
done 👌

**Comment by pc223** [comment]
I think this will works,  just make sure we got the messages.mo files in the zip release and we good.

How do you test this? bump plugin.json to 1.2.0.test? or something a bit stealthy? :smile:

**Comment by jjw24** [comment]
i added a condition to run the deploy zip only when it's on master. @deefrawley can you kick off a manual workflow job via the actions tab please

**Comment by deefrawley** [comment]
Merge PR then run on Main? Won't that trigger the deploy?

**Comment by jjw24** [comment]
no,  i mean this

image

then you can select the branch in this pr

**Comment by deefrawley** [comment]
image

Only main to choose from

**Comment by jjw24** [comment]
hmm ok, might be because this is a fork branch. let me test it in my fork

**Comment by jjw24** [comment]
we good 😃 

image

the workflow can only trigger branches in your own repo i suppose. run only on main condition can help you test your branches without publishing the zip

**Comment by deefrawley** [comment]
As always thanks. So I can merge the PR but not run the CI until Flow v1.8 is released?

**Comment by jjw24** [comment]
Nah you can merge, should create a 1.2.1 release with the translation files. This plugin should work with current flow release already

**Pull request merged**
